import { type NextPage } from "next"
import { useSession } from "next-auth/react";
import Head from "next/head"
import { type FC } from "react";
import { PostList } from "~/features/Post";

const Home: NextPage = () => (
  <>
    <Head>
      <title>Chronicles</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/logo.png" />
    </Head>
    <main>
      <DefaultAuth />
    </main>
  </>
);

export default Home

const DefaultAuth: FC = () => {
  const { data: session } = useSession()

  return (
    <>
      {session ? (
        <PostList />
      ) : (
        <span style={{ textAlign: 'center' }}>Not logged in</span>
      )}
    </>
  );
};
