import { type NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => (
    <>
      <Head>
        <title>Chronicles</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <div>home</div>
      </main>
    </>
  );

export default Home
